### ISSUE TITLE
连接nas自带的MariaDB报错

### ISSUE THREAD

**Issue by xiaozhubin** [blossom-editor/blossom#56]
群晖NAS，连接了自带的MariaDB 10，日志显示数据库连接成功。但是后续还是报错了。
手动插入了 ` INSERT INTO base_sys_param (id, param_name, param_value, param_desc, open_state, cre_time, upd_time) SELECT 1, 'WEB_ARTICLE_URL', 'https://www.domain.com/blossom/#/articles?articleId=', '博客端文章地址,用于PC端直接调往WEB端阅读文章', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM base_sys_param WHERE id = 1)`
但不管用。

以下是日志信息。

2023-12-27T03:29:35.040636866Z,stdout,	... 34 common frames omitted

2023-12-27T03:29:35.040593444Z,stdout,	at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:261)

2023-12-27T03:29:35.040551385Z,stdout,	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)

2023-12-27T03:29:35.040508513Z,stdout,	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)

2023-12-27T03:29:35.040466060Z,stdout,	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)

2023-12-27T03:29:35.040423555Z,stdout,	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)

2023-12-27T03:29:35.040379342Z,stdout,	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)

2023-12-27T03:29:35.040338237Z,stdout,	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)

2023-12-27T03:29:35.040290416Z,stdout,	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)

2023-12-27T03:29:35.040233310Z,stdout,Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT 1 FROM base_sys_param WHERE id = 1)' at line 1

2023-12-27T03:29:35.040191227Z,stdout,	... 24 common frames omitted

2023-12-27T03:29:35.040144848Z,stdout,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)

2023-12-27T03:29:35.040097485Z,stdout,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)

2023-12-27T03:29:35.040053210Z,stdout,	at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.afterPropertiesSet(AbstractScriptDatabaseInitializer.java:65)

2023-12-27T03:29:35.040007038Z,stdout,	at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.initializeDatabase(AbstractScriptDatabaseInitializer.java:75)

2023-12-27T03:29:35.039962568Z,stdout,	at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.applySchemaScripts(AbstractScriptDatabaseInitializer.java:97)

2023-12-27T03:29:35.039917816Z,stdout,	at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.applyScripts(AbstractScriptDatabaseInitializer.java:107)

2023-12-27T03:29:35.039873451Z,stdout,	at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.runScripts(AbstractScriptDatabaseInitializer.java:145)

2023-12-27T03:29:35.039828635Z,stdout,	at org.springframework.boot.jdbc.init.DataSourceScriptDatabaseInitializer.runScripts(DataSourceScriptDatabaseInitializer.java:90)

2023-12-27T03:29:35.039783974Z,stdout,	at org.springframework.jdbc.datasource.init.DatabasePopulatorUtils.execute(DatabasePopulatorUtils.java:54)

2023-12-27T03:29:35.039737572Z,stdout,	at org.springframework.jdbc.datasource.init.ResourceDatabasePopulator.populate(ResourceDatabasePopulator.java:254)

2023-12-27T03:29:35.039684244Z,stdout,	at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:282)

2023-12-27T03:29:35.039586686Z,stdout,"Caused by: org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #2 of URL [file:/application/BOOT-INF/classes/schema-mysql.sql]: INSERT INTO base_sys_param (id, param_name, param_value, param_desc, open_state, cre_time, upd_time) SELECT 1, 'WEB_ARTICLE_URL', 'https://www.domain.com/blossom/#/articles?articleId=', '博客端文章地址,用于PC端直接调往WEB端阅读文章', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM base_sys_param WHERE id = 1); nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT 1 FROM base_sys_param WHERE id = 1)' at line 1
"
2023-12-27T03:29:35.039542436Z,stdout,	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)

2023-12-27T03:29:35.039500963Z,stdout,	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)

2023-12-27T03:29:35.039457900Z,stdout,	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)

2023-12-27T03:29:35.039413124Z,stdout,	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)

2023-12-27T03:29:35.039371016Z,stdout,	at java.lang.reflect.Method.invoke(Method.java:498)

2023-12-27T03:29:35.039321921Z,stdout,	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

2023-12-27T03:29:35.039277328Z,stdout,	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

2023-12-27T03:29:35.039230719Z,stdout,	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2023-12-27T03:29:35.039187873Z,stdout,	at com.blossom.backend.APP.main(APP.java:26)

2023-12-27T03:29:35.039144398Z,stdout,	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)

2023-12-27T03:29:35.039097839Z,stdout,	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)

2023-12-27T03:29:35.039055046Z,stdout,	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)

2023-12-27T03:29:35.039008403Z,stdout,	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)

2023-12-27T03:29:35.038964353Z,stdout,	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)

2023-12-27T03:29:35.038918702Z,stdout,	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)

2023-12-27T03:29:35.038872915Z,stdout,	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)

2023-12-27T03:29:35.038831313Z,stdout,	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)

2023-12-27T03:29:35.038787618Z,stdout,	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)

2023-12-27T03:29:35.038740988Z,stdout,	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)

2023-12-27T03:29:35.038671669Z,stdout,	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)

2023-12-27T03:29:35.038624839Z,stdout,	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)

2023-12-27T03:29:35.038576586Z,stdout,	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)

2023-12-27T03:29:35.038530778Z,stdout,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)

2023-12-27T03:29:35.038482483Z,stdout,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)

2023-12-27T03:29:35.038428536Z,stdout,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)

2023-12-27T03:29:35.038187217Z,stdout,"[0;39morg.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #2 of URL [file:/application/BOOT-INF/classes/schema-mysql.sql]: INSERT INTO base_sys_param (id, param_name, param_value, param_desc, open_state, cre_time, upd_time) SELECT 1, 'WEB_ARTICLE_URL', 'https://www.domain.com/blossom/#/articles?articleId=', '博客端文章地址,用于PC端直接调往WEB端阅读文章', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM base_sys_param WHERE id = 1); nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT 1 FROM base_sys_param WHERE id = 1)' at line 1
"
2023-12-27T03:29:35.038001077Z,stdout,[0;39m[31m11:29:35.036 ERROR[main      ] [62.81] o.s.boot.SpringApplication     821: Application run failed

2023-12-27T03:29:34.972935252Z,stdout,Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.

2023-12-27T03:29:34.972897290Z,stdout,

2023-12-27T03:29:34.972677461Z,stdout,[0;39m[37m11:29:34.971 INFO [main      ] [62.81] valuationReportLoggingListener 136: 

2023-12-27T03:29:34.924709509Z,stdout,[0;39m[37m11:29:34.922 INFO [main      ] [62.81] o.a.c.core.StandardService     173: Stopping service [Tomcat]

2023-12-27T03:29:34.873730674Z,stdout,"[0;39m[33m11:29:34.873 WARN [main      ] [62.81] letWebServerApplicationContext 591: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #2 of URL [file:/application/BOOT-INF/classes/schema-mysql.sql]: INSERT INTO base_sys_param (id, param_name, param_value, param_desc, open_state, cre_time, upd_time) SELECT 1, 'WEB_ARTICLE_URL', 'https://www.domain.com/blossom/#/articles?articleId=', '博客端文章地址,用于PC端直接调往WEB端阅读文章', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM base_sys_param WHERE id = 1); nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT 1 FROM base_sys_param WHERE id = 1)' at line 1
"
2023-12-27T03:29:34.162622584Z,stdout,[0;39m[37m11:29:34.161 INFO [main      ] [62.81] c.b.c.c.c.CaffeineCacheConfig  34 : [   CACHE] 缓存注解使用 : Caffeine

2023-12-27T03:29:28.772237791Z,stdout,[0;39m[37m11:29:28.771 INFO [main      ] [62.81] c.b.c.d.i.SlowSQLInterceptor   51 : [    BASE] 慢查询时长为 : 200ms

2023-12-27T03:29:28.387519769Z,stdout,[0;39m[37m11:29:28.298 INFO [main      ] [62.81] c.b.b.base.auth.AuthProperties 166: [AUTHORIZ] └──────────┴──────────┴─────────┴────────────┘

2023-12-27T03:29:28.387453622Z,stdout,[0;39m[37m11:29:28.295 INFO [main      ] [62.81] c.b.b.base.auth.AuthProperties 156: [AUTHORIZ] | blossom  | 6 Hour   | true    | true       | [password]

2023-12-27T03:29:28.387400343Z,stdout,[0;39m[37m11:29:28.293 INFO [main      ] [62.81] c.b.b.base.auth.AuthProperties 137: [AUTHORIZ] ├──────────┼──────────┼─────────┼────────────┤

2023-12-27T03:29:28.387344296Z,stdout,[0;39m[37m11:29:28.292 INFO [main      ] [62.81] c.b.b.base.auth.AuthProperties 136: [AUTHORIZ] | ClientId | Duration | Refresh | MultiPlace |

2023-12-27T03:29:28.387237416Z,stdout,[0;39m[37m11:29:28.287 INFO [main      ] [62.81] c.b.b.base.auth.AuthProperties 135: [AUTHORIZ] ┌──────────┬──────────┬─────────┬────────────┐

2023-12-27T03:29:28.286704448Z,stdout,"[0;39m[37m11:29:28.285 INFO [main      ] [62.81] c.b.b.base.auth.AuthProperties 134: [AUTHORIZ] 授权类型:caffeine, Client:客户端, Duration(h):授权时长(小时), Refresh:请求刷新授权, MultiPlace:允许多处登录
"
2023-12-27T03:29:27.469487803Z,stdout,[0;39m[37m11:29:27.468 INFO [main      ] [62.81] letWebServerApplicationContext 292: Root WebApplicationContext: initialization completed in 8852 ms

2023-12-27T03:29:27.468127475Z,stdout,[0;39m[37m11:29:27.467 INFO [main      ] [62.81] o.a.c.c.C.[.[localhost].[/]    173: Initializing Spring embedded WebApplicationContext

2023-12-27T03:29:27.262204805Z,stdout,[0;39m[37m11:29:27.261 INFO [main      ] [62.81] o.a.c.core.StandardEngine      173: Starting Servlet engine: [Apache Tomcat/9.0.74]

2023-12-27T03:29:27.260129450Z,stdout,[0;39m[37m11:29:27.259 INFO [main      ] [62.81] o.a.c.core.StandardService     173: Starting service [Tomcat]

2023-12-27T03:29:19.601589809Z,stdout,[0;39m[37m11:29:18.266 INFO [main      ] [62.81] com.blossom.backend.APP        637: The following 1 profile is active: "prod"

2023-12-27T03:29:19.601509650Z,stdout,[37m11:29:18.257 INFO [main      ] [62.81] com.blossom.backend.APP        55 : Starting APP v1.11.0-SNAPSHOT using Java 1.8.0_392 on d82e1f6de7b5 with PID 7 (/application/BOOT-INF/classes started by root in /application)

2023-12-27T03:29:19.601474762Z,stdout,

2023-12-27T03:29:19.601421066Z,stdout,╚═════╝  ╚══════╝  ╚═════╝  ╚══════╝ ╚══════╝  ╚═════╝  ╚═╝     ╚═╝

2023-12-27T03:29:19.601372908Z,stdout,██████╔╝ ███████╗ ╚██████╔╝ ███████║ ███████║ ╚██████╔╝ ██║ ╚═╝ ██║

2023-12-27T03:29:19.601324705Z,stdout,██╔══██╗ ██║      ██║   ██║ ╚════██║ ╚════██║ ██║   ██║ ██║╚██╔╝██║

2023-12-27T03:29:19.601281281Z,stdout,██████╔╝ ██║      ██║   ██║ ███████╗ ███████╗ ██║   ██║ ██╔████╔██║

2023-12-27T03:29:19.601223755Z,stdout,██╔══██╗ ██║      ██╔═══██╗ ██╔════╝ ██╔════╝ ██╔═══██╗ ████╗ ████║

2023-12-27T03:29:19.601133887Z,stdout,██████╗  ██╗       ██████╗  ███████╗ ███████╗  ██████╗  ███╗   ███╗

2023-12-27T03:29:18.034995280Z,stdout,[0;39m

2023-12-27T03:29:17.709795186Z,stdout,[CHECK] ==========================================================================================================================

2023-12-27T03:29:17.709600489Z,stdout,[0;39m[33m11:29:17.708 WARN [main      ] [62.81] .b.b.c.PropertiesCheckListener 78 : 数据库链接检查完毕

2023-12-27T03:29:16.772024011Z,stdout,[0;39m[37m11:29:16.769 INFO [nd-preinit] [  .  ] o.h.v.internal.util.Version    21 : HV000001: Hibernate Validator 6.2.5.Final

2023-12-27T03:29:16.451274307Z,stdout,[CHECK] ==========================================================================================================================

2023-12-27T03:29:16.451241007Z,stdout,

2023-12-27T03:29:16.451207200Z,stdout,

2023-12-27T03:29:16.451160974Z,stdout,正在检查数据库连接

2023-12-27T03:29:16.451117403Z,stdout,

2023-12-27T03:29:16.450934094Z,stdout,[0;39m[33m11:29:16.449 WARN [main      ] [62.81] .b.b.c.PropertiesCheckListener 68 : 

2023-12-27T03:29:16.445905460Z,stdout,

2023-12-27T03:29:16.445865140Z,stdout,

2023-12-27T03:29:16.445816600Z,stdout,[CHECK] ==========================================================================================================================

2023-12-27T03:29:16.445764550Z,stdout,[CHECK] 图片存储: /home/bl/img/

2023-12-27T03:29:16.445717331Z,stdout,[CHECK] 图片前缀: 

2023-12-27T03:29:16.445598859Z,stdout,[CHECK] 数据库密码: 

2023-12-27T03:29:16.445548047Z,stdout,[CHECK] 数据库用户: 

2023-12-27T03:29:16.445468405Z,stdout,[CHECK] 数据库配置: jdbc:mysql://000.000.0.0:3306/blossom?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&allowMultiQueries=true&useSSL=false&&serverTimezone=GMT%2B8

2023-12-27T03:29:16.445418721Z,stdout,[CHECK] ==========================================================================================================================

2023-12-27T03:29:16.445370246Z,stdout,"[CHECK] 使用环境: [prod], 版本: [1.11.0-SNAPSHOT]
"
2023-12-27T03:29:16.445319799Z,stdout,[CHECK] ==========================================================================================================================

2023-12-27T03:29:16.445275249Z,stdout,

2023-12-27T03:29:16.445240062Z,stdout,

2023-12-27T03:29:16.445187931Z,stdout,正在检查 Blossom 后台配置项

2023-12-27T03:29:16.445100163Z,stdout,

2023-12-27T03:29:16.444303009Z,stdout,[33m11:29:16.420 WARN [main      ] [62.81] .b.b.c.PropertiesCheckListener 37 :

**Comment by xiaozzzi** [comment]
可以尝试试用更高版本的 mariadb，或者使用 mysql8
